version: 2.1

default: &default
  docker:
    - image: cimg/go:1.17
      auth:
        username: $DOCKERHUB_USER
        password: $DOCKERHUB_PASSWORD

jobs:
  build:
    <<: *default
    steps:
      - checkout
      - run: make build
  lint:
    <<: *default
    steps:
      - checkout
      - run: make lint
  test:
    <<: *default
    steps:
      - checkout
      - run: make test
  bench:
    <<: *default
    steps:
      - checkout
      - run: make bench

workflows:
  version: 2
  general:
    jobs:
      - build:
          context: org-global
      - lint:
          context: org-global
      - test:
          context: org-global
      - bench:
          context: org-global